### ISSUE TITLE
Error occurred When using OpenCV Ver4.0.0 in ass1

### ISSUE THREAD

**Issue by fool8474** [IPCVLabEdu/assignments#5]
in ass1_imgroc.cpp's func 'backprojectHistogram' occurs error
maybe it will occurred by dst.create(srcMat.size(), CV_64FC1); code

![image](https://user-images.githubusercontent.com/28250401/49231767-fb381200-f435-11e8-93c0-48ae6f3233f6.png)
using openCV ver3.4.4

![image](https://user-images.githubusercontent.com/28250401/49231883-33d7eb80-f436-11e8-820c-8c088a479b09.png)
using openCV ver4.0.0
error occurred

**Comment by AI-MD** [comment]
따라서 4.0버전으로 돌려서 실행하려면 
//dst.create(srcMat.size(), CV_64FC1);  
double 형태가 아닌
dst.create(srcMat.size(), CV_8UC1);
unsigned char 형태의 0~255  값으로 safe한코드로 작성해야 정상적으로 output Image를 띄울 수 있습니다. 
if (val > 255)
	val = 255;
if (val < 0)
        val = 0;
outputProb.at<uchar>(y, x) = val;

**Comment by insurgent92** [comment]
@fool8474 @AI-MD 
Thank you for reporting your first issue :D 
I wanna see specific error logs on your terminal (you have to specify what errors are).

**Note that All issues have to be distinct**
I can't understand why your source codes are not working in opencv v4.0.0
(actually i wrote this assignments with opencv 4.0.0)

tips. 
Additionally You can take `code links` like below. its fancier! 
https://github.com/IPCVLabEdu/assignments/blob/cbbe56df5b78fa34deb1bc639f7c25cf76d7a725/imgproc.cpp#L22

**Comment by fool8474** [comment]
@insurgent92 
This is the source of Error Code

![1](https://user-images.githubusercontent.com/28250401/49325960-7dd3e500-f58e-11e8-931a-475b524abf02.PNG)
this is console log
![2](https://user-images.githubusercontent.com/28250401/49325962-80363f00-f58e-11e8-83db-2776394cbc86.png)
and this is object where the error occurs.

https://github.com/IPCVLabEdu/assignments/blob/865a3b5e2e608290e8c0b71aafe3f9f77a5b8d7e/imgproc.cpp#L20
This is the only code involved in this mat. I didn't see any difference in code with other people.

**Comment by insurgent92** [comment]
OpenCV 3.4 버전대로 다운그레이드 하시기 바랍니다.
